CREATE EXTERNAL TABLE IF NOT EXISTS openpowerlifting.lifter (
    Name string,
    Sex string,
    Event string,
    Equipment string,
    Age float,
    AgeClass string,
    BirthYearClass string,
    Division string,
    BodyweightKg float,
    WeightClassKg string,
    Squat1Kg float,
    Squat2Kg float,
    Squat3Kg float,
    Squat4Kg float,
    Best3SquatKg float,
    Bench1Kg float,
    Bench2Kg float,
    Bench3Kg float,
    Bench4Kg float,
    Best3BenchKg float,
    Deadlift1Kg float,
    Deadlift2Kg float,
    Deadlift3Kg float,
    Deadlift4Kg float,
    Best3DeadliftKg float,
    TotalKg float,
    Place string,
    Dots float,
    Wilks float,
    Glossbrenner float,
    Goodlift float,
    Tested string,
    Country string,
    State string,
    Federation string,
    ParentFederation string,
    Date string,
    MeetCountry string,
    MeetState string,
    MeetTown string,
    MeetName string,
    Sanctioned string
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES ('field.delim' = ',')
LOCATION 's3://tdouglas-data-prod-useast2/data/raw/openpowerlifting/lifter/'
TBLPROPERTIES ("skip.header.line.count" = "1");
