CREATE TABLE IF NOT EXISTS cleansed.openpowerlifting (
  name string,
  sex string,
  event string,
  equipment string,
  age string,
  age_class string,
  birth_year_class string,
  division string,
  bodyweight_kg string,
  weightclass_kg string,
  squat_1_kg string,
  squat_2_kg string,
  squat_3_kg string,
  squat_4_kg string,
  best_3_squat_kg string,
  bench_1_kg string,
  bench_2_kg string,
  bench_3_kg string,
  bench_4_kg string,
  best_3_bench_kg string,
  deadlift_1_kg string,
  deadlift_2_kg string,
  deadlift_3_kg string,
  deadlift_4_kg string,
  best_3_deadlift_kg string,
  total_kg string,
  place string,
  dots string,
  wilks string,
  glossbrenner string,
  goodlift string,
  tested string,
  country string,
  state string,
  federation string,
  parent_federation string,
  date string,
  meet_country string,
  meet_state string,
  meet_town string,
  meet_name string,
  sanctioned string,
  row_hash string,
  source_system string,
  source_table string,
  inserted_at timestamp,
  job_name string,
  job_id string,
  job_run_id string,
  is_deleted boolean
 ) 
PARTITIONED BY (bucket(16, row_hash)) 
LOCATION 's3://dev-use2-tedsand-iceberg-s3/warehouse/cleansed.db/openpowerlifting' 
TBLPROPERTIES (
  'table_type'='ICEBERG',
  'format'='parquet',
  'write_compression'='snappy'
)
